version: '3.9'

services:

  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    networks:
      net-main:
        ipv4_address: "${MONGO_INITDB_IP}"
    ports:
     - "27017:27017"
    volumes:
      - "./volumes/mongo/:/data/db/"

  jpeg_snipe:
    env_file: .env
    volumes:
      - "./:$APP_PATH"
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "/root/app/run.sh"]
      interval: 30s
      timeout: 2m30s
      retries: 10
      start_period: 1ms
    depends_on:
      - mongo
    networks:
      net-main:
    command: 
      tail -f /var/log/nftspy.log
    ports:
     - "80:8080"      

networks:
  net-main:
    driver: bridge
    ipam:
     config:
       - subnet: 172.19.0.0/16
         gateway: 172.19.0.1